### ISSUE TITLE
Some errors running the tutorials

### ISSUE THREAD

**Issue by JoffJones** [neurolib-dev/neurolib#99] opened 2020-08-10 12:10 UTC
Hi Caglar,

What an amazing tool! I've managed to simulate FC using your notebooks, but I've ran into some problems just running the notebooks as they are using the example code and data. Maybe it is a problem with my installation or virtual environment (conda environment attached, python 3.8)? 
[neurolib2_packages.txt] (https://github.com/neurolib-dev/neurolib/files/5050707/neurolib2_packages.txt)

With example-1-aln-paramter-exploration I get the following error:

parameters = ParameterSpace({"mue_ext_mean": np.linspace(0, 3, 21), "mui_ext_mean": np.linspace(0, 3, 21)})
search = BoxSearch(aln, parameters, filename="example-1.hdf")

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-6346e36f062a> in <module>
      1 parameters = ParameterSpace({"mue_ext_mean": np.linspace(0, 3, 21), "mui_ext_mean": np.linspace(0, 3, 21)})
      2 # info: chose np.linspace(0, 3, 21) or more, values here are low for testing
----> 3 search = BoxSearch(aln, parameters)

~/.conda/envs/neurolib2/lib/python3.8/site-packages/neurolib/optimize/exploration/exploration.py in __init__(self, model, parameterSpace, evalFunction, filename, saveAllModelOutputs)
     71         # bool to check whether pypet was initialized properly
     72         self.initialized = False
---> 73         self.initializeExploration(self.filename)
     74 
     75     def initializeExploration(self, filename="exploration.hdf"):

~/.conda/envs/neurolib2/lib/python3.8/site-packages/neurolib/optimize/exploration/exploration.py in initializeExploration(self, filename)
     93 
     94         # set up the pypet environment
---> 95         env = pypet.Environment(
     96             trajectory=trajectoryName,
     97             filename=trajectoryfilename,

~/.conda/envs/neurolib2/lib/python3.8/site-packages/pypet/utils/configparsing.py in new_func(env, *args, **kwargs)
     18         # Pass the config data to the kwargs
     19         new_kwargs = config_interpreter.interpret()
---> 20         init_func(env, *args, **new_kwargs)
     21         # Add parameters and config data from the `.ini` file
     22         config_interpreter.add_parameters(env.traj)

~/.conda/envs/neurolib2/lib/python3.8/site-packages/pypet/utils/decorators.py in new_func(*args, **kwargs)
    161                     kwargs[new_name] = value
    162 
--> 163             return func(*args, **kwargs)
    164 
    165         return new_func

~/.conda/envs/neurolib2/lib/python3.8/site-packages/pypet/utils/decorators.py in new_func(*args, **kwargs)
    161                     kwargs[new_name] = value
    162 
--> 163             return func(*args, **kwargs)
    164 
    165         return new_func

~/.conda/envs/neurolib2/lib/python3.8/site-packages/pypet/utils/decorators.py in new_func(*args, **kwargs)
    161                     kwargs[new_name] = value
    162 
--> 163             return func(*args, **kwargs)
    164 
    165         return new_func

~/.conda/envs/neurolib2/lib/python3.8/site-packages/pypet/utils/decorators.py in new_func(*args, **kwargs)
    161                     kwargs[new_name] = value
    162 
--> 163             return func(*args, **kwargs)
    164 
    165         return new_func

~/.conda/envs/neurolib2/lib/python3.8/site-packages/pypet/utils/decorators.py in new_func(*args, **kwargs)
    161                     kwargs[new_name] = value
    162 
--> 163             return func(*args, **kwargs)
    164 
    165         return new_func

~/.conda/envs/neurolib2/lib/python3.8/site-packages/pypet/utils/decorators.py in new_func(*args, **kwargs)
    161                     kwargs[new_name] = value
    162 
--> 163             return func(*args, **kwargs)
    164 
    165         return new_func

~/.conda/envs/neurolib2/lib/python3.8/site-packages/pypet/utils/decorators.py in new_func(*args, **kwargs)
    161                     kwargs[new_name] = value
    162 
--> 163             return func(*args, **kwargs)
    164 
    165         return new_func

~/.conda/envs/neurolib2/lib/python3.8/site-packages/pypet/pypetlogging.py in new_func(self, *args, **kwargs)
    170             _change_logging_kwargs(kwargs)
    171 
--> 172         return func(self, *args, **kwargs)
    173 
    174     return new_func

~/.conda/envs/neurolib2/lib/python3.8/site-packages/pypet/environment.py in __init__(self, trajectory, add_time, comment, dynamic_imports, wildcard_functions, automatic_storing, log_config, log_stdout, report_progress, multiproc, ncores, use_scoop, use_pool, freeze_input, timeout, cpu_cap, memory_cap, swap_cap, niceness, wrap_mode, queue_maxsize, port, gc_interval, clean_up_runs, immediate_postproc, resumable, resume_folder, delete_resume, storage_service, git_repository, git_message, git_fail, sumatra_project, sumatra_reason, sumatra_label, do_single_runs, graceful_exit, lazy_debug, **kwargs)
   1143                                                log_stdout=log_stdout,
   1144                                                report_progress=report_progress)
-> 1145         self._logging_manager.check_log_config()
   1146         self._logging_manager.add_null_handler()
   1147         self._set_logger()

~/.conda/envs/neurolib2/lib/python3.8/site-packages/pypet/pypetlogging.py in check_log_config(self)
    521             if isinstance(self.log_config, str):
    522                 if not os.path.isfile(self.log_config):
--> 523                     raise ValueError('Could not find the logger init file '
    524                                      '`%s`.' % self.log_config)
    525                 parser = NoInterpolationParser()

ValueError: Could not find the logger init file `./neurolib/utils/pypet_logging.ini`.

Any help would be appreciated!
Many thanks,
Joff

**Comment by caglorithm** [comment] 2020-08-10 12:21
Hi Joff! I think we can fix your error :) It looks like you don't have this file available `./neurolib/utils/pypet_logging.ini`. Could you check if it's on your computer? How did you install `neurolib`? Using the pip package or the github repo? Maybe you need to pull the most recent version using `git pull`.

**Comment by JoffJones** [comment] 2020-08-10 14:16
Hi! I used pip for the install and that file doesn't seem to exist, would you suggest using git for the install instead?

Many thanks,
Joff

**Comment by caglorithm** [comment] 2020-08-10 14:31
Gotcha! Yes, the problem is that we forgot to add this file to `MANIFEST.in` and therefore it hasn't been packaged in the pypi. Haven't noticed that since now so I'm glad that you've reported the issue. I will build a new package and upload it to the repository so that `pip install --upgrade neurolib` should fetch the newest version. It should be done in an hour or so but if you want to get started immediately, you can simply install the package from the Github repo here which should work!

Thanks again!

**Comment by JoffJones** [comment] 2020-08-10 14:34
Great, thanks so much!

**Comment by caglorithm** [comment] 2020-08-10 18:09
Closed by #100

**Closed** 2020-08-10 18:11 UTC
Labels: bug
