### ISSUE TITLE
If set explicitly, local connectivity weights for ALNNode change after running the model

### ISSUE THREAD

**Issue by mattiasJohnson** [neurolib-dev/neurolib#203] opened 2022-05-09 11:19 UTC
## Issue
If set explicitly, `ALNThlmNet.ALNNode_0.local_connectivity` will change value after a run.

## Replicate
```python
import numpy as np
from neurolib.models.multimodel import MultiModel

Cmat = np.array([[0.0, 0.12], [1.2, 0.0]])
Dmat = np.array([[0.0, 13.0], [13.0, 0.0]])
model = MultiModel(ALNThalamusMiniNetwork(Cmat, Dmat))

model.params["duration"] = 5000
model.params["ALNThlmNet.ALNNode_0.local_connectivity"] = np.array([[0.24691358, 0.75757576], [0.23076923, 1.52439024]])

print(model.params["ALNThlmNet.ALNNode_0.local_connectivity"])
model.run()
print(model.params["ALNThlmNet.ALNNode_0.local_connectivity"])
```
Output:
```python
[[0.24691358 0.75757576]
 [0.23076923 1.52439024]]
[[0.20322105 1.14784206]
 [0.17751479 4.64753122]]
```

Where I'm using `ALNThalamusMiniNetwork` from [`aln_thalamus.py`](https://github.com/jajcayn/thalamocortical_model_study/blob/main/aln_thalamus.py) in `thalamocortical_model_study` 

## More details

I haven't done too deep investigation but it seems like the ALN local weights change directly  in the `run()` method at `self._update_model_params()`, more specifically the `new_model_params` that gets returned from `flatten_nested_dict()` called in `self._sync_model_params()` ([link to line](https://github.com/neurolib-dev/neurolib/blob/714eef48616af0ebdb62decc84826221472398f9/neurolib/models/multimodel/model.py#L90)) contains the changed local weights. The problem seems isolated to the aln local weights, setting the local weights of the thalamus node and running works as expected.

**Comment by jajcayn** [comment] 2022-05-09 12:11
Hey @mattiasJohnson,

thanks for opening the issue. This is actually not a bug. ALN is the only model, that rescales connectivity. In other words, the connectivity you provide is multiplied by synaptic time constants and divided by maximum current (see https://github.com/neurolib-dev/neurolib/blob/714eef48616af0ebdb62decc84826221472398f9/neurolib/models/multimodel/builder/aln.py#L742-L761)

You can also check that when you update parameters of this ALN node, the connectivity is rescaled again, so it works for exploration and optimization without any problems (https://github.com/neurolib-dev/neurolib/blob/714eef48616af0ebdb62decc84826221472398f9/neurolib/models/multimodel/builder/aln.py#L826)

**Comment by mattiasJohnson** [comment] 2022-05-17 07:47
Just a related note on something I encountered while testing. If one imports a complete `params` dotdict and replaces the original `multimodel.params` through assignment then the ALNs local connectivity will keep on changing for every run. Replacing the model's dotdict through assignment (as opposed to looping through the dictionary just changing each value of the original dotdict object) might not be the best code practice but I still thought I'd post it here if any future user of neurolib would encounter it too so it's documented because it wasn't super obvious to find what was going wrong.

```python
from params_thalamocortical import imported_params
from neurolib.models.multimodel import MultiModel

model_multi = MultiModel(ALNThalamusMiniNetwork(
    np.array([[0.0, 0.12], [1.2, 0.0]]),
    np.array([[0.0, 13],   [13, 0.0]]),) 
    )

model_multi.params = imported_params

model_multi.run()
print(model_multi.params["ALNThlmNet.ALNNode_0.local_connectivity"])

# Output after running this code cell some times:
# [[1.33015058e-02 3.85715452e+02]
# [4.50845372e-03 2.78604742e+07]]
```

**Comment by caglorithm** [comment] 2022-05-17 18:05
Thank you for the comment! Closing :)

**Closed by caglorithm** 2022-05-17 18:05 UTC
